import json
import codecs
import ast

de = {
    "nav": { "services": "Dienstleistungen", "portfolio": "Portfolio", "process": "Prozess", "about": "Über uns", "contact": "Kontakt", "startProject": "Projekt starten" },
    "hero": { "eyebrow": "ERSTKLASSIGE WEB- & SOFTWAREENTWICKLUNG", "headline": "Wir entwickeln digitale<br />Produkte, die <span>skalieren</span>", "subhead": "Von maßgeschneiderten Shopify-Shops bis hin zu Enterprise-Software – CodeLoop liefert hochleistungsfähige Lösungen, die auf Ihre Geschäftsziele zugeschnitten sind.", "primaryBtn": "Projekt starten", "secondaryBtn": "Unsere Arbeit" },
    "trust": { "stat1Value": "50+", "stat1Label": "Projekte geliefert", "stat2Value": "99%", "stat2Label": "Kundenzufriedenheit", "stat3Value": "5+", "stat3Label": "Jahre Erfahrung", "stat4Value": "24/7", "stat4Label": "Support verfügbar" },
    "services": { "label": "Unsere Expertise", "heading": "Alles, was Sie für den <span>Online-Erfolg</span> brauchen", "subheading": "Wir schreiben nicht nur Code. Wir entwickeln skalierbare, leistungsstarke Lösungen, die Umsatz generieren.", "customWebTitle": "Webentwicklung", "customWebDesc": "Leistungsstarke Websites mit React, Next.js und Node.js. Optimiert für Geschwindigkeit.", "shopifyTitle": "Shopify-Entwicklung", "shopifyDesc": "Individuelle Shopify-Themes und komplexe App-Integrationen.", "wordpressTitle": "WordPress & WooCommerce", "wordpressDesc": "Sichere und skalierbare WordPress-Lösungen auf Enterprise-Niveau.", "crmTitle": "CRM & Software", "crmDesc": "Maßgeschneiderte interne Tools und CRM-Systeme.", "seoTitle": "Technisches SEO", "seoDesc": "Tiefe technische Optimierung für bessere Rankings und Konversionen.", "supportTitle": "Support & Wartung", "supportDesc": "24/7-Monitoring, Sicherheitsupdates und kontinuierliche Weiterentwicklung." },
    "portfolio": { "label": "Ausgewählte Arbeit", "heading": "Projekte, die <span>Ergebnisse</span> liefern", "subheading": "Eine Auswahl unserer besten Arbeiten.", "startProjectBtn": "Projekt starten", "filterAll": "Alle Projekte", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "PROJEKT ANSEHEN", "privateClient": "PRIVATKUNDE", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "Wie wir arbeiten", "heading": "Ein bewährter Prozess für <span>großartige Ergebnisse</span>", "subheading": "Von der ersten Nachricht bis zum Post-Launch-Support.", "step1Title": "Anfrage", "step1Desc": "Sie melden sich. Wir hören aufmerksam zu, um Ihre Vision zu verstehen.", "step2Title": "Vorschlag", "step2Desc": "Wir senden einen detaillierten Vorschlag mit Umfang, Zeitplan und Preisen.", "step3Title": "Design", "step3Desc": "Unsere Designer erstellen perfekte Mockups, bis Sie zufrieden sind.", "step4Title": "Entwicklung", "step4Desc": "Die Entwicklung beginnt mit sauberem Code und regelmäßigen Updates.", "step5Title": "Launch", "step5Desc": "Wir gehen live und starten Ihr Projekt mit vollständigem Monitoring.", "step6Title": "Support", "step6Desc": "Laufender Support und Wachstum – wir sind Ihr langfristiger technischer Partner." },
    "about": { "label": "Unsere Geschichte", "heading": "Von Entwicklern gebaut,<br />durch <span>Ergebnisse</span> angetrieben", "p1": "CodeLoop wurde mit einer klaren Mission gegründet: Enterprise-Web- und Softwareentwicklung für Unternehmen jeder Größe anzubieten.", "p2": "Von Solo-Gründern bis hin zu wachsenden Unternehmen – wir haben Kunden weltweit geholfen.", "remoteLabel1": "Verfügbar in allen großen Zeitzonen", "remoteLabel2": "Wir synchronisieren uns mit Ihrem Zeitplan", "techTitle": "Unsere Technologien" },
    "testimonials": { "label": "Kundenfeedback", "heading": "Weltweit von Kunden <span>vertraut</span>", "subheading": "Hier ist, was unsere Kunden über die Arbeit mit uns sagen.", "leaveReview": "Bewertung schreiben", "empty1": "Kundenbewertungen kommen bald.", "empty2": "Haben Sie mit uns gearbeitet? Kontaktieren Sie uns!" },
    "contact": { "label": "Kontakt aufnehmen", "heading": "Lassen Sie uns zusammen etwas <span>Großartiges</span> bauen", "subheading": "Erzählen Sie uns von Ihrem Projekt.", "emailLabel": "E-Mail", "whatsappLabel": "WhatsApp", "scheduleLabel": "Gespräch planen", "scheduleValue": "Kostenlose Beratung buchen", "fullName": "Vollständiger Name *", "email": "E-Mail-Adresse *", "serviceNeeded": "Benötigter Service *", "selectService": "Service wählen...", "sWeb": "Webentwicklung", "sShopify": "Shopify-Entwicklung", "sWordpress": "WordPress-Entwicklung", "sCrm": "CRM / Software", "sStore": "Online-Shop", "sWoo": "WooCommerce", "sOther": "Andere", "budgetRange": "Budgetrahmen", "selectBudget": "Budget wählen...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "Noch nicht sicher", "disclaimer": "Endgültiger Preis hängt vom Umfang ab.", "submit": "Anfrage senden" },
    "footer": { "copyright": "© 2026 CodeLoop. Alle Rechte vorbehalten.", "linksLabel": "Schnelllinks" },
    "feedback": { "modalTitle": "Teilen Sie Ihre Erfahrung", "modalSubtitle": "Wir schätzen Ihr Feedback!", "nameLabel": "Ihr Name *", "roleLabel": "Rolle / Firma (Optional)", "ratingLabel": "Bewertung *", "messageLabel": "Ihr Feedback *", "messagePlaceholder": "Erzählen Sie uns von Ihrer Erfahrung...", "submit": "Bewertung senden" }
}

fr = {
    "nav": { "services": "Services", "portfolio": "Portfolio", "process": "Processus", "about": "À propos", "contact": "Contact", "startProject": "Démarrer un projet" },
    "hero": { "eyebrow": "DÉVELOPPEMENT WEB ET LOGICIEL DE CLASSE MONDIALE", "headline": "Nous construisons des produits digitaux qui <span>évoluent</span>", "subhead": "Des boutiques Shopify sur mesure aux logiciels d'entreprise personnalisés, CodeLoop fournit des solutions de haute performance adaptées à vos objectifs.", "primaryBtn": "Démarrer un projet", "secondaryBtn": "Voir notre travail" },
    "trust": { "stat1Value": "50+", "stat1Label": "Projets livrés", "stat2Value": "99%", "stat2Label": "Satisfaction client", "stat3Value": "5+", "stat3Label": "Années d'expérience", "stat4Value": "24/7", "stat4Label": "Support disponible" },
    "services": { "label": "Notre Expertise", "heading": "Tout ce dont vous avez besoin pour <span>réussir en ligne</span>", "subheading": "Nous ne nous contentons pas d'écrire du code. Nous construisons des solutions évolutives conçues pour générer des revenus.", "customWebTitle": "Développement Web", "customWebDesc": "Sites performants avec React, Next.js et Node.js.", "shopifyTitle": "Développement Shopify", "shopifyDesc": "Thèmes Shopify personnalisés et intégrations complexes.", "wordpressTitle": "WordPress & WooCommerce", "wordpressDesc": "Solutions WordPress de niveau entreprise.", "crmTitle": "CRM & Logiciels", "crmDesc": "Outils internes et systèmes CRM sur mesure.", "seoTitle": "SEO Technique", "seoDesc": "Optimisation technique approfondie pour un meilleur classement.", "supportTitle": "Support & Maintenance", "supportDesc": "Surveillance 24/7 et développement continu." },
    "portfolio": { "label": "Travaux Réalisés", "heading": "Des projets qui génèrent des <span>résultats</span>", "subheading": "Une sélection de nos meilleurs travaux.", "startProjectBtn": "Démarrer un projet", "filterAll": "Tous les projets", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "VOIR LE PROJET", "privateClient": "CLIENT PRIVÉ", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "Notre Méthode", "heading": "Un processus éprouvé pour <span>d'excellents résultats</span>", "subheading": "De votre premier message au support post-lancement.", "step1Title": "Demande", "step1Desc": "Nous vous écoutons attentivement pour comprendre votre vision.", "step2Title": "Proposition", "step2Desc": "Nous envoyons une proposition détaillée et transparente.", "step3Title": "Design", "step3Desc": "Nos designers créent des maquettes parfaites.", "step4Title": "Développement", "step4Desc": "Développement avec un code propre et des mises à jour régulières.", "step5Title": "Lancement", "step5Desc": "Nous déployons en production avec un suivi complet.", "step6Title": "Support", "step6Desc": "Support continu — nous sommes votre partenaire technique." },
    "about": { "label": "Notre Histoire", "heading": "Conçu par des développeurs,<br />axé sur les <span>résultats</span>", "p1": "CodeLoop a été fondé avec une mission claire : apporter le développement d'entreprise aux entreprises de toutes tailles.", "p2": "Des fondateurs solo aux entreprises en croissance, nous aidons les clients du monde entier.", "remoteLabel1": "Disponible sur tous les fuseaux horaires", "remoteLabel2": "Nous nous synchronisons avec votre emploi du temps", "techTitle": "Nos Technologies" },
    "testimonials": { "label": "Avis Clients", "heading": "Des clients <span>du monde entier</span> nous font confiance", "subheading": "Voici ce que nos clients disent de CodeLoop.", "leaveReview": "Laisser un avis", "empty1": "Les avis clients arrivent bientôt.", "empty2": "Avez-vous travaillé avec nous ? Contactez-nous !" },
    "contact": { "label": "Contactez-nous", "heading": "Construisons quelque chose de <span>grand ensemble</span>", "subheading": "Parlez-nous de votre projet.", "emailLabel": "Email", "whatsappLabel": "WhatsApp", "scheduleLabel": "Planifier un appel", "scheduleValue": "Réserver une consultation gratuite", "fullName": "Nom complet *", "email": "Adresse email *", "serviceNeeded": "Service requis *", "selectService": "Sélectionnez un service...", "sWeb": "Développement Web", "sShopify": "Développement Shopify", "sWordpress": "Développement WordPress", "sCrm": "CRM / Logiciel", "sStore": "Boutique en ligne", "sWoo": "WooCommerce", "sOther": "Autre", "budgetRange": "Budget", "selectBudget": "Sélectionnez un budget...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "Pas encore sûr", "disclaimer": "Le prix final dépend de la portée du projet.", "submit": "Envoyer" },
    "footer": { "copyright": "© 2026 CodeLoop. Tous droits réservés.", "linksLabel": "Liens rapides" },
    "feedback": { "modalTitle": "Partagez votre expérience", "modalSubtitle": "Nous apprécions vos retours !", "nameLabel": "Votre nom *", "roleLabel": "Rôle / Entreprise (Optionnel)", "ratingLabel": "Évaluation *", "messageLabel": "Votre avis *", "messagePlaceholder": "Parlez-nous de votre expérience...", "submit": "Envoyer l'avis" }
}

es = {
    "nav": { "services": "Servicios", "portfolio": "Portafolio", "process": "Proceso", "about": "Nosotros", "contact": "Contacto", "startProject": "Iniciar Proyecto" },
    "hero": { "eyebrow": "DESARROLLO WEB Y DE SOFTWARE DE CLASE MUNDIAL", "headline": "Construimos productos digitales que <span>escalan</span>", "subhead": "Desde tiendas Shopify a medida hasta software empresarial personalizado, CodeLoop ofrece soluciones de alto rendimiento adaptadas a sus objetivos.", "primaryBtn": "Iniciar Proyecto", "secondaryBtn": "Ver nuestro trabajo" },
    "trust": { "stat1Value": "50+", "stat1Label": "Proyectos", "stat2Value": "99%", "stat2Label": "Satisfacción", "stat3Value": "5+", "stat3Label": "Años de experiencia", "stat4Value": "24/7", "stat4Label": "Soporte" },
    "services": { "label": "Nuestra Experiencia", "heading": "Todo lo que necesitas para <span>tener éxito online</span>", "subheading": "No solo escribimos código. Construimos soluciones escalables diseñadas para generar ingresos.", "customWebTitle": "Desarrollo Web", "customWebDesc": "Sitios web de alto rendimiento con React, Next.js y Node.js.", "shopifyTitle": "Desarrollo Shopify", "shopifyDesc": "Temas personalizados e integraciones complejas.", "wordpressTitle": "WordPress y WooCommerce", "wordpressDesc": "Soluciones de nivel empresarial.", "crmTitle": "CRM y Software", "crmDesc": "Herramientas internas a medida.", "seoTitle": "SEO Técnico", "seoDesc": "Optimización técnica profunda para un mejor posicionamiento.", "supportTitle": "Soporte y Mantenimiento", "supportDesc": "Monitoreo 24/7 y desarrollo continuo." },
    "portfolio": { "label": "Trabajo Destacado", "heading": "Proyectos que impulsan <span>resultados</span>", "subheading": "Una selección de nuestros mejores trabajos.", "startProjectBtn": "Iniciar Proyecto", "filterAll": "Todos", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "VER PROYECTO", "privateClient": "CLIENTE PRIVADO", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "Cómo trabajamos", "heading": "Un proceso probado para <span>grandes resultados</span>", "subheading": "Desde su primer mensaje hasta el soporte posterior al lanzamiento.", "step1Title": "Consulta", "step1Desc": "Escuchamos atentamente su visión.", "step2Title": "Propuesta", "step2Desc": "Enviamos una propuesta detallada y transparente.", "step3Title": "Diseño", "step3Desc": "Nuestros diseñadores crean maquetas perfectas.", "step4Title": "Desarrollo", "step4Desc": "Desarrollo con código limpio y actualizaciones.", "step5Title": "Lanzamiento", "step5Desc": "Desplegamos con monitoreo completo.", "step6Title": "Soporte", "step6Desc": "Soporte continuo: somos su socio técnico." },
    "about": { "label": "Nuestra Historia", "heading": "Construido por desarrolladores,<br />impulsado por <span>resultados</span>", "p1": "CodeLoop se fundó con una misión clara: llevar el desarrollo empresarial a todas las empresas.", "p2": "Desde fundadores solitarios hasta empresas en crecimiento, ayudamos a clientes en todo el mundo.", "remoteLabel1": "Disponible en todas las zonas horarias", "remoteLabel2": "Nos sincronizamos con su horario", "techTitle": "Tecnologías que dominamos" },
    "testimonials": { "label": "Comentarios", "heading": "Clientes de todo el <span>mundo</span> confían en nosotros", "subheading": "Esto es lo que dicen nuestros clientes.", "leaveReview": "Dejar una reseña", "empty1": "Las reseñas llegarán pronto.", "empty2": "¿Ha trabajado con nosotros? ¡Contáctenos!" },
    "contact": { "label": "Contáctenos", "heading": "Construyamos algo <span>grande juntos</span>", "subheading": "Cuéntenos sobre su proyecto.", "emailLabel": "Email", "whatsappLabel": "WhatsApp", "scheduleLabel": "Agendar llamada", "scheduleValue": "Reserva gratuita de 30 min", "fullName": "Nombre completo *", "email": "Correo electrónico *", "serviceNeeded": "Servicio necesario *", "selectService": "Seleccionar servicio...", "sWeb": "Desarrollo Web", "sShopify": "Desarrollo Shopify", "sWordpress": "Desarrollo WordPress", "sCrm": "CRM / Software", "sStore": "Tienda en línea", "sWoo": "WooCommerce", "sOther": "Otro", "budgetRange": "Presupuesto", "selectBudget": "Seleccionar presupuesto...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "No estoy seguro", "disclaimer": "El precio final depende del alcance.", "submit": "Enviar" },
    "footer": { "copyright": "© 2026 CodeLoop. Todos los derechos reservados.", "linksLabel": "Enlaces rápidos" },
    "feedback": { "modalTitle": "Comparte tu experiencia", "modalSubtitle": "¡Valoramos tu opinión!", "nameLabel": "Tu Nombre *", "roleLabel": "Rol / Empresa (Opcional)", "ratingLabel": "Calificación *", "messageLabel": "Tu Reseña *", "messagePlaceholder": "Cuéntanos tu experiencia...", "submit": "Enviar reseña" }
}

it = {
    "nav": { "services": "Servizi", "portfolio": "Portfolio", "process": "Processo", "about": "Chi siamo", "contact": "Contatto", "startProject": "Inizia Progetto" },
    "hero": { "eyebrow": "SVILUPPO WEB E SOFTWARE DI LIVELLO MONDIALE", "headline": "Creiamo prodotti digitali che <span>scalano</span>", "subhead": "Da negozi Shopify su misura a software aziendali personalizzati, CodeLoop offre soluzioni ad alte prestazioni.", "primaryBtn": "Inizia Progetto", "secondaryBtn": "Il nostro lavoro" },
    "trust": { "stat1Value": "50+", "stat1Label": "Progetti", "stat2Value": "99%", "stat2Label": "Clienti Soddisfatti", "stat3Value": "5+", "stat3Label": "Anni di esperienza", "stat4Value": "24/7", "stat4Label": "Supporto" },
    "services": { "label": "La nostra esperienza", "heading": "Tutto ciò di cui hai bisogno per il <span>successo online</span>", "subheading": "Costruiamo soluzioni scalabili progettate per generare entrate.", "customWebTitle": "Sviluppo Web", "customWebDesc": "Siti web ad alte prestazioni con React, Next.js e Node.js.", "shopifyTitle": "Sviluppo Shopify", "shopifyDesc": "Temi Shopify personalizzati e integrazioni complesse.", "wordpressTitle": "WordPress & WooCommerce", "wordpressDesc": "Soluzioni di livello aziendale.", "crmTitle": "CRM & Software", "crmDesc": "Strumenti interni e sistemi CRM su misura.", "seoTitle": "SEO Tecnico", "seoDesc": "Ottimizzazione tecnica per un migliore posizionamento.", "supportTitle": "Supporto e Manutenzione", "supportDesc": "Monitoraggio 24/7 e aggiornamenti." },
    "portfolio": { "label": "Lavori In Evidenza", "heading": "Progetti che portano <span>risultati</span>", "subheading": "Una selezione dei nostri migliori lavori.", "startProjectBtn": "Inizia Progetto", "filterAll": "Tutti", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "VEDI PROGETTO", "privateClient": "CLIENTE PRIVATO", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "Come Lavoriamo", "heading": "Un processo collaudato per <span>ottimi risultati</span>", "subheading": "Dal primo messaggio al supporto post-lancio.", "step1Title": "Richiesta", "step1Desc": "Ascoltiamo attentamente la tua visione.", "step2Title": "Proposta", "step2Desc": "Inviamo una proposta dettagliata e trasparente.", "step3Title": "Design", "step3Desc": "I nostri designer creano mockup perfetti.", "step4Title": "Sviluppo", "step4Desc": "Sviluppo con codice pulito e aggiornamenti regolari.", "step5Title": "Lancio", "step5Desc": "Distribuiamo in produzione con monitoraggio.", "step6Title": "Supporto", "step6Desc": "Supporto continuo — siamo il tuo partner tecnico." },
    "about": { "label": "La nostra storia", "heading": "Costruito da sviluppatori,<br />guidato dai <span>risultati</span>", "p1": "CodeLoop è stata fondata con una missione: portare lo sviluppo di livello aziendale ad aziende di tutte le dimensioni.", "p2": "Dai fondatori solisti alle aziende in crescita, abbiamo aiutato clienti in tutto il mondo.", "remoteLabel1": "Disponibile in tutti i fusi orari", "remoteLabel2": "Ci sincronizziamo con i tuoi orari", "techTitle": "Tecnologie che padroneggiamo" },
    "testimonials": { "label": "Feedback dei Clienti", "heading": "Scelti da clienti in tutto <span>il mondo</span>", "subheading": "Ecco cosa dicono i nostri clienti.", "leaveReview": "Lascia una recensione", "empty1": "Recensioni in arrivo.", "empty2": "Hai lavorato con noi? Contattaci!" },
    "contact": { "label": "Contattaci", "heading": "Costruiamo qualcosa di <span>grande insieme</span>", "subheading": "Parlaci del tuo progetto.", "emailLabel": "Email", "whatsappLabel": "WhatsApp", "scheduleLabel": "Prenota chiamata", "scheduleValue": "Consulenza gratuita 30 min", "fullName": "Nome completo *", "email": "Indirizzo email *", "serviceNeeded": "Servizio necessario *", "selectService": "Seleziona un servizio...", "sWeb": "Sviluppo Web", "sShopify": "Sviluppo Shopify", "sWordpress": "Sviluppo WordPress", "sCrm": "CRM / Software", "sStore": "Negozio Online", "sWoo": "WooCommerce", "sOther": "Altro", "budgetRange": "Budget", "selectBudget": "Seleziona budget...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "Non sono sicuro", "disclaimer": "Il prezzo finale dipende dall'ambito del progetto.", "submit": "Invia" },
    "footer": { "copyright": "© 2026 CodeLoop. Tutti i diritti riservati.", "linksLabel": "Link Rapidi" },
    "feedback": { "modalTitle": "Condividi la tua esperienza", "modalSubtitle": "Apprezziamo il tuo feedback!", "nameLabel": "Il tuo nome *", "roleLabel": "Ruolo / Azienda (Opzionale)", "ratingLabel": "Valutazione *", "messageLabel": "La tua recensione *", "messagePlaceholder": "Raccontaci della tua esperienza...", "submit": "Invia Recensione" }
}

nl = {
    "nav": { "services": "Diensten", "portfolio": "Portfolio", "process": "Proces", "about": "Over ons", "contact": "Contact", "startProject": "Start Project" },
    "hero": { "eyebrow": "WERELDKLASSE WEB & SOFTWARE ONTWIKKELING", "headline": "Wij bouwen digitale<br />producten die <span>schalen</span>", "subhead": "CodeLoop levert hoogwaardige oplossingen op maat van uw zakelijke doelen.", "primaryBtn": "Start Project", "secondaryBtn": "Bekijk ons werk" },
    "trust": { "stat1Value": "50+", "stat1Label": "Projecten Opgeleverd", "stat2Value": "99%", "stat2Label": "Klanttevredenheid", "stat3Value": "5+", "stat3Label": "Jaren Ervaring", "stat4Value": "24/7", "stat4Label": "Ondersteuning" },
    "services": { "label": "Onze Expertise", "heading": "Alles wat u nodig heeft voor <span>online succes</span>", "subheading": "Wij bouwen schaalbare oplossingen om inkomsten te genereren.", "customWebTitle": "Webontwikkeling", "customWebDesc": "Snelle websites met React, Next.js en Node.js.", "shopifyTitle": "Shopify Ontwikkeling", "shopifyDesc": "Op maat gemaakte Shopify thema's en integraties.", "wordpressTitle": "WordPress & WooCommerce", "wordpressDesc": "WordPress oplossingen op ondernemingsniveau.", "crmTitle": "CRM & Software", "crmDesc": "Interne tools en CRM systemen op maat.", "seoTitle": "Technische SEO", "seoDesc": "Diepgaande optimalisatie voor betere rankings.", "supportTitle": "Ondersteuning & Onderhoud", "supportDesc": "24/7 monitoring en continue ontwikkeling." },
    "portfolio": { "label": "Uitgelicht Werk", "heading": "Projecten die <span>resultaten</span> opleveren", "subheading": "Een selectie van ons beste werk.", "startProjectBtn": "Start Project", "filterAll": "Alle", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "BEKIJK PROJECT", "privateClient": "PRIVÉKLANT", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "Hoe wij werken", "heading": "Een bewezen proces voor <span>geweldige resultaten</span>", "subheading": "Van uw eerste bericht tot ondersteuning na de lancering.", "step1Title": "Aanvraag", "step1Desc": "Wij luisteren om uw visie te begrijpen.", "step2Title": "Voorstel", "step2Desc": "Wij sturen een gedetailleerd voorstel.", "step3Title": "Ontwerp", "step3Desc": "Onze ontwerpers maken perfecte mockups.", "step4Title": "Ontwikkeling", "step4Desc": "Schone code met regelmatige updates.", "step5Title": "Lancering", "step5Desc": "We lanceren uw project met volledige monitoring.", "step6Title": "Ondersteuning", "step6Desc": "Continue ondersteuning — uw technische partner." },
    "about": { "label": "Ons Verhaal", "heading": "Gebouwd door ontwikkelaars,<br />gedreven door <span>resultaten</span>", "p1": "CodeLoop is opgericht om bedrijven van elke omvang enterprise-grade ontwikkeling te bieden.", "p2": "We hebben klanten over de hele wereld geholpen.", "remoteLabel1": "Beschikbaar in alle tijdzones", "remoteLabel2": "Wij synchroniseren met uw schema", "techTitle": "Onze Technologieën" },
    "testimonials": { "label": "Klantenfeedback", "heading": "Vertrouwd door klanten <span>wereldwijd</span>", "subheading": "Dit is wat onze klanten zeggen.", "leaveReview": "Plaats een review", "empty1": "Klantbeoordelingen komen eraan.", "empty2": "Heeft u met ons gewerkt? Neem contact op!" },
    "contact": { "label": "Neem contact op", "heading": "Laten we samen iets <span>geweldigs</span> bouwen", "subheading": "Vertel ons over uw project.", "emailLabel": "E-mail", "whatsappLabel": "WhatsApp", "scheduleLabel": "Plan een gesprek", "scheduleValue": "Boek een gratis consult", "fullName": "Volledige naam *", "email": "E-mailadres *", "serviceNeeded": "Benodigde service *", "selectService": "Selecteer een service...", "sWeb": "Webontwikkeling", "sShopify": "Shopify Ontwikkeling", "sWordpress": "WordPress Ontwikkeling", "sCrm": "CRM / Software", "sStore": "Webshop", "sWoo": "WooCommerce", "sOther": "Anders", "budgetRange": "Budget", "selectBudget": "Selecteer budget...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "Nog niet zeker", "disclaimer": "Definitieve prijs hangt af van het project.", "submit": "Verstuur" },
    "footer": { "copyright": "© 2026 CodeLoop. Alle rechten voorbehouden.", "linksLabel": "Snelle links" },
    "feedback": { "modalTitle": "Deel uw ervaring", "modalSubtitle": "Wij waarderen uw feedback!", "nameLabel": "Uw Naam *", "roleLabel": "Rol / Bedrijf (Optioneel)", "ratingLabel": "Beoordeling *", "messageLabel": "Uw Review *", "messagePlaceholder": "Vertel ons over uw ervaring...", "submit": "Review versturen" }
}

hi = {
    "nav": { "services": "सेवाएं", "portfolio": "पोर्टफोलियो", "process": "प्रक्रिया", "about": "हमारे बारे में", "contact": "संपर्क", "startProject": "प्रोजेक्ट शुरू करें" },
    "hero": { "eyebrow": "विश्व स्तरीय वेब और सॉफ्टवेयर विकास", "headline": "हम ऐसे डिजिटल उत्पाद बनाते हैं जो <span>स्केल</span> करते हैं", "subhead": "शॉपीफाई स्टोर्स से लेकर एंटरप्राइज कस्टम सॉफ्टवेयर तक, CodeLoop उच्च प्रदर्शन समाधान प्रदान करता है।", "primaryBtn": "प्रोजेक्ट शुरू करें", "secondaryBtn": "हमारा काम देखें" },
    "trust": { "stat1Value": "50+", "stat1Label": "वितरित प्रोजेक्ट", "stat2Value": "99%", "stat2Label": "ग्राहक संतुष्टि", "stat3Value": "5+", "stat3Label": "वर्षों का अनुभव", "stat4Value": "24/7", "stat4Label": "समर्थन उपलब्ध" },
    "services": { "label": "हमारी विशेषज्ञता", "heading": "ऑनलाइन <span>सफलता</span> के लिए आपको जो कुछ भी चाहिए", "subheading": "हम स्केलेबल, उच्च-प्रदर्शन समाधान बनाते हैं।", "customWebTitle": "कस्टम वेब विकास", "customWebDesc": "React और Node.js के साथ उच्च प्रदर्शन वेबसाइटें।", "shopifyTitle": "शॉपीफाई विकास", "shopifyDesc": "कस्टम शॉपीफाई थीम और एकीकरण।", "wordpressTitle": "वर्डप्रेस और वूकामर्स", "wordpressDesc": "एंटरप्राइज-ग्रेड वर्डप्रेस समाधान।", "crmTitle": "कस्टम CRM और सॉफ्टवेयर", "crmDesc": "कस्टम आंतरिक उपकरण और CRM सिस्टम।", "seoTitle": "तकनीकी SEO", "seoDesc": "बेहतर रैंकिंग के लिए तकनीकी अनुकूलन।", "supportTitle": "निरंतर समर्थन", "supportDesc": "24/7 निगरानी और सुरक्षा।" },
    "portfolio": { "label": "फीचर्ड कार्य", "heading": "वे प्रोजेक्ट जो <span>परिणाम</span> लाते हैं", "subheading": "हमारे बेहतरीन काम का चयन।", "startProjectBtn": "प्रोजेक्ट शुरू करें", "filterAll": "सभी", "filterWordpress": "वर्डप्रेस", "filterShopify": "शॉपीफाई", "filterSEO": "एसईओ", "viewProject": "प्रोजेक्ट देखें", "privateClient": "निजी ग्राहक", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "हम कैसे काम करते हैं", "heading": "बेहतरीन परिणामों के लिए एक <span>प्रमाणित प्रक्रिया</span>", "subheading": "आपके पहले संदेश से लेकर लॉन्च के बाद के समर्थन तक।", "step1Title": "पूछताछ", "step1Desc": "हम आपकी दृष्टि को समझने के लिए ध्यान से सुनते हैं।", "step2Title": "प्रस्ताव", "step2Desc": "हम एक विस्तृत प्रस्ताव भेजते हैं।", "step3Title": "डिजाइन", "step3Desc": "हम सटीक डिजाइन बनाते हैं।", "step4Title": "विकास", "step4Desc": "स्वच्छ कोड और नियमित अपडेट के साथ विकास।", "step5Title": "लॉन्च", "step5Desc": "हम आपके प्रोजेक्ट को लॉन्च करते हैं।", "step6Title": "समर्थन", "step6Desc": "निरंतर समर्थन — हम आपके तकनीकी भागीदार हैं।" },
    "about": { "label": "हमारी कहानी", "heading": "डेवलपर्स द्वारा निर्मित, <span>परिणामों</span> द्वारा संचालित", "p1": "CodeLoop को हर आकार के व्यवसायों में वेब और सॉफ्टवेयर विकास लाने के लिए स्थापित किया गया था।", "p2": "हमने दुनिया भर के ग्राहकों की मदद की है।", "remoteLabel1": "सभी प्रमुख समय क्षेत्रों में उपलब्ध", "remoteLabel2": "हम आपके कार्यक्रम के साथ सिंक करते हैं", "techTitle": "हम जिन तकनीकों में माहिर हैं" },
    "testimonials": { "label": "ग्राहक प्रतिक्रिया", "heading": "दुनिया भर में ग्राहकों द्वारा <span>विश्वसनीय</span>", "subheading": "देखें कि हमारे ग्राहक हमारे बारे में क्या कहते हैं।", "leaveReview": "समीक्षा छोड़ें", "empty1": "समीक्षाएं जल्द आ रही हैं।", "empty2": "क्या आपने हमारे साथ काम किया है? संपर्क करें!" },
    "contact": { "label": "संपर्क करें", "heading": "आइए एक साथ <span>महान</span> कुछ बनाएं", "subheading": "हमें अपने प्रोजेक्ट के बारे में बताएं।", "emailLabel": "ईमेल", "whatsappLabel": "व्हाट्सएप", "scheduleLabel": "कॉल शेड्यूल करें", "scheduleValue": "मुफ़्त 30-मिनट का परामर्श", "fullName": "पूरा नाम *", "email": "ईमेल पता *", "serviceNeeded": "आवश्यक सेवा *", "selectService": "एक सेवा चुनें...", "sWeb": "वेब विकास", "sShopify": "शॉपीफाई विकास", "sWordpress": "वर्डप्रेस विकास", "sCrm": "CRM / सॉफ्टवेयर", "sStore": "ऑनलाइन स्टोर", "sWoo": "वूकामर्स", "sOther": "अन्य", "budgetRange": "बजट", "selectBudget": "बजट चुनें...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "सुनिश्चित नहीं है", "disclaimer": "अंतिम मूल्य परियोजना के दायरे पर निर्भर करता है।", "submit": "भेजें" },
    "footer": { "copyright": "© 2026 CodeLoop. सर्वाधिकार सुरक्षित।", "linksLabel": "त्वरित लिंक" },
    "feedback": { "modalTitle": "अपना अनुभव साझा करें", "modalSubtitle": "हम आपकी प्रतिक्रिया को महत्व देते हैं!", "nameLabel": "आपका नाम *", "roleLabel": "भूमिका / कंपनी", "ratingLabel": "रेटिंग *", "messageLabel": "आपकी प्रतिक्रिया *", "messagePlaceholder": "हमें अपने अनुभव के बारे में बताएं...", "submit": "समीक्षा सबमिट करें" }
}

fil = {
    "nav": { "services": "Serbisyo", "portfolio": "Portfolio", "process": "Proseso", "about": "Tungkol sa Amin", "contact": "Kontak", "startProject": "Simulan ang Proyekto" },
    "hero": { "eyebrow": "WORLD-CLASS WEB & SOFTWARE DEVELOPMENT", "headline": "Gumagawa kami ng mga digital na produkto na <span>lumalago</span>", "subhead": "Nag-aalok ang CodeLoop ng mga solusyon para sa iyong mga layunin sa negosyo.", "primaryBtn": "Simulan ang Proyekto", "secondaryBtn": "Tingnan ang aming gawa" },
    "trust": { "stat1Value": "50+", "stat1Label": "Proyektong Naihatid", "stat2Value": "99%", "stat2Label": "Kasiyahan ng Kliyente", "stat3Value": "5+", "stat3Label": "Taon ng Karanasan", "stat4Value": "24/7", "stat4Label": "Available ang Suporta" },
    "services": { "label": "Aming Kadalubhasaan", "heading": "Lahat ng kailangan mo para <span>magtagumpay online</span>", "subheading": "Gumagawa kami ng maaasahang mga solusyon para sa iyong negosyo.", "customWebTitle": "Web Development", "customWebDesc": "Mabibilis na website gamit ang React at Node.js.", "shopifyTitle": "Shopify Development", "shopifyDesc": "Custom Shopify themes at integrations.", "wordpressTitle": "WordPress at WooCommerce", "wordpressDesc": "Enterprise-grade na mga solusyon sa WordPress.", "crmTitle": "Custom CRM at Software", "crmDesc": "Mga custom na internal tools at CRM systems.", "seoTitle": "Technical SEO", "seoDesc": "Malalim na technical optimization.", "supportTitle": "Suporta at Maintenance", "supportDesc": "24/7 na pagsubaybay at seguridad." },
    "portfolio": { "label": "Itinatampok na Gawa", "heading": "Mga proyekto na nagdadala ng <span>resulta</span>", "subheading": "Isang pagpipilian ng aming pinakamahusay na gawa.", "startProjectBtn": "Simulan ang Proyekto", "filterAll": "Lahat", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "TINGNAN ANG PROYEKTO", "privateClient": "PRIBADONG KLIYENTE", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "Paano Kami Magtrabaho", "heading": "Isang subok na proseso para sa <span>magagandang resulta</span>", "subheading": "Mula sa iyong unang mensahe hanggang sa suporta.", "step1Title": "Pagtatanong", "step1Desc": "Makikinig kami para maunawaan ang iyong pananaw.", "step2Title": "Panukala", "step2Desc": "Magpapadala kami ng detalyadong panukala.", "step3Title": "Disenyo", "step3Desc": "Gumagawa ang aming mga designer ng perpektong mockups.", "step4Title": "Pag-develop", "step4Desc": "Pag-develop na may malinis na code.", "step5Title": "Paglulunsad", "step5Desc": "Ilulunsad namin ang iyong proyekto.", "step6Title": "Suporta", "step6Desc": "Patuloy na suporta — kami ang iyong partner." },
    "about": { "label": "Aming Kwento", "heading": "Binuo ng mga developer,<br />dala ng <span>mga resulta</span>", "p1": "Itinatag ang CodeLoop upang magdala ng software development sa mga negosyo.", "p2": "Nakatulong kami sa mga kliyente sa buong mundo.", "remoteLabel1": "Available sa lahat ng time zones", "remoteLabel2": "Nag-synchronize kami sa iyong iskedyul", "techTitle": "Mga Teknolohiya" },
    "testimonials": { "label": "Feedback ng Kliyente", "heading": "Pinagkakatiwalaan ng mga kliyente <span>sa buong mundo</span>", "subheading": "Narito ang sinasabi ng aming mga kliyente.", "leaveReview": "Mag-iwan ng Review", "empty1": "Malapit na ang mga review ng kliyente.", "empty2": "Nakatrabaho mo na ba kami? Makipag-ugnayan!" },
    "contact": { "label": "Makipag-ugnayan", "heading": "Bumuo tayo ng <span>magandang bagay nang magkasama</span>", "subheading": "Sabihin sa amin ang tungkol sa iyong proyekto.", "emailLabel": "Email", "whatsappLabel": "WhatsApp", "scheduleLabel": "Mag-schedule ng Tawag", "scheduleValue": "Mag-book ng libreng konsultasyon", "fullName": "Buong Pangalan *", "email": "Email Address *", "serviceNeeded": "Kailangang Serbisyo *", "selectService": "Pumili ng serbisyo...", "sWeb": "Web Development", "sShopify": "Shopify Development", "sWordpress": "WordPress Development", "sCrm": "CRM / Software", "sStore": "Online Store", "sWoo": "WooCommerce", "sOther": "Iba pa", "budgetRange": "Badyet", "selectBudget": "Pumili ng badyet...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "Hindi pa sigurado", "disclaimer": "Nakadepende ang huling presyo sa proyekto.", "submit": "Ipadala" },
    "footer": { "copyright": "© 2026 CodeLoop. All rights reserved.", "linksLabel": "Quick Links" },
    "feedback": { "modalTitle": "Ibahagi ang Iyong Karanasan", "modalSubtitle": "Pinahahalagahan namin ang iyong feedback!", "nameLabel": "Iyong Pangalan *", "roleLabel": "Papel / Kumpanya (Opsyonal)", "ratingLabel": "Rating *", "messageLabel": "Iyong Feedback *", "messagePlaceholder": "Sabihin sa amin ang tungkol sa iyong karanasan...", "submit": "I-submit ang Review" }
}

zh = {
    "nav": { "services": "服务", "portfolio": "作品集", "process": "流程", "about": "关于", "contact": "联系", "startProject": "开始项目" },
    "hero": { "eyebrow": "世界级的Web和软件开发", "headline": "我们构建可<span>扩展</span>的数字产品", "subhead": "从定制的Shopify商店到企业级定制软件，CodeLoop提供为您业务目标量身定制的高性能解决方案。", "primaryBtn": "开始项目", "secondaryBtn": "查看我们的工作" },
    "trust": { "stat1Value": "50+", "stat1Label": "交付项目", "stat2Value": "99%", "stat2Label": "客户满意度", "stat3Value": "5+", "stat3Label": "年经验", "stat4Value": "24/7", "stat4Label": "提供支持" },
    "services": { "label": "我们的专业", "heading": "您在线<span>成功</span>所需的一切", "subheading": "我们构建可扩展的高性能解决方案，旨在增加收入。", "customWebTitle": "定制Web开发", "customWebDesc": "使用React, Next.js和Node.js构建的高性能定制网站。", "shopifyTitle": "Shopify开发", "shopifyDesc": "定制的Shopify主题和复杂的应用程序集成。", "wordpressTitle": "WordPress和WooCommerce", "wordpressDesc": "企业级WordPress解决方案。", "crmTitle": "定制CRM和软件", "crmDesc": "定制内部工具、仪表板和CRM系统。", "seoTitle": "技术SEO", "seoDesc": "深入的技术优化以提高排名。", "supportTitle": "持续支持与维护", "supportDesc": "24/7监控、安全补丁和持续功能开发。" },
    "portfolio": { "label": "特色作品", "heading": "推动<span>结果</span>的项目", "subheading": "我们在各行各业的精选作品。", "startProjectBtn": "开始项目", "filterAll": "全部", "filterWordpress": "WordPress", "filterShopify": "Shopify", "filterSEO": "SEO", "viewProject": "查看项目", "privateClient": "私人客户", "tagWordpress": "WordPress", "tagShopify": "Shopify", "tagSEO": "SEO", "p1": "Master Tiger General Transport", "p2": "Capel Estates", "p3": "BillGreen", "p4": "Stylfox", "p5": "MyChildsRoom", "p6": "Mida Living", "p7": "Vapzone.ae", "p8": "VPDAZZLE.AE", "p9": "VapDubai.ae", "p10": "VapeDubaiKing", "p11": "Vaps.ae", "p12": "Vaporweb.ae", "p13": "VapeShopDubai.ae", "p14": "Drywall Takeoff Services", "p15": "Lumber Estimating Services", "p16": "Bids Analytics LLC", "p17": "Pure Whole Melt Home", "p18": "Sprayed Tech Solutions", "p19": "Vape SEO", "p20": "CortexZ", "p21": "CloudNine Clothing" },
    "process": { "label": "我们的工作方式", "heading": "获得<span>卓越结果</span>的成熟流程", "subheading": "从您的第一条消息到发布后的支持。", "step1Title": "咨询", "step1Desc": "我们仔细倾听以了解您的愿景。", "step2Title": "提案", "step2Desc": "我们发送详细的提案和透明的定价。", "step3Title": "设计", "step3Desc": "我们的设计师制作完美的模型。", "step4Title": "开发", "step4Desc": "使用整洁的代码和定期更新进行开发。", "step5Title": "发布", "step5Desc": "我们将项目部署到生产环境。", "step6Title": "支持", "step6Desc": "持续的支持和更新——我们是您的技术合作伙伴。" },
    "about": { "label": "我们的故事", "heading": "由开发人员构建，受<span>结果</span>驱动", "p1": "CodeLoop成立的使命明确：将企业级Web和软件开发带给各个规模的企业。", "p2": "我们帮助了世界各地的客户实现他们的数字目标。", "remoteLabel1": "适用于所有主要时区", "remoteLabel2": "我们与您的日程保持同步", "techTitle": "我们掌握的技术" },
    "testimonials": { "label": "客户反馈", "heading": "深受全球客户<span>信任</span>", "subheading": "听听我们的客户怎么说。", "leaveReview": "发表评论", "empty1": "客户评论即将推出。", "empty2": "您和我们合作过吗？联系我们！" },
    "contact": { "label": "取得联系", "heading": "让我们一起建立<span>伟大的事物</span>", "subheading": "告诉我们您的项目。", "emailLabel": "电子邮件", "whatsappLabel": "WhatsApp", "scheduleLabel": "预约通话", "scheduleValue": "预约免费30分钟咨询", "fullName": "全名 *", "email": "电子邮件地址 *", "serviceNeeded": "所需服务 *", "selectService": "选择服务...", "sWeb": "Web开发", "sShopify": "Shopify开发", "sWordpress": "WordPress开发", "sCrm": "CRM / 软件", "sStore": "在线商店", "sWoo": "WooCommerce", "sOther": "其他", "budgetRange": "预算范围", "selectBudget": "选择预算...", "b1": "$1,000 – $3,000", "b2": "$3,000 – $8,000", "b3": "$8,000 – $20,000", "b4": "$20,000+", "bUnsure": "还不确定", "disclaimer": "最终价格取决于项目范围。", "submit": "发送" },
    "footer": { "copyright": "© 2026 CodeLoop. 保留所有权利。", "linksLabel": "快速链接" },
    "feedback": { "modalTitle": "分享您的经验", "modalSubtitle": "我们重视您的反馈！", "nameLabel": "您的名字 *", "roleLabel": "职位 / 公司（可选）", "ratingLabel": "评分 *", "messageLabel": "您的反馈 *", "messagePlaceholder": "告诉我们您的体验...", "submit": "提交评论" }
}

with codecs.open("/Users/abuzar/Downloads/CodeLoop/js/translations.js", "r", "utf-8") as jsf:
    content = jsf.read()
content = content.replace("};\n", "")

with codecs.open("/Users/abuzar/Downloads/CodeLoop/js/translations.js", "w", "utf-8") as out:
    out.write(content)
    out.write(',\n')
    out.write('  "de": ' + json.dumps(de, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "fr": ' + json.dumps(fr, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "es": ' + json.dumps(es, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "it": ' + json.dumps(it, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "nl": ' + json.dumps(nl, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "hi": ' + json.dumps(hi, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "fil": ' + json.dumps(fil, ensure_ascii=False, indent=4) + ',\n')
    out.write('  "zh": ' + json.dumps(zh, ensure_ascii=False, indent=4) + '\n')
    out.write('};\n')
